POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "Your Email",
    "password": "Your Password"
}

###
GET http://localhost:5000/user

###
POST http://localhost:5000/user
Content-Type: application/json

{
    "fullname": "Your Fullname",
    "email": "Your Email"
}